name: 🐛 Bug Report
description: Create a report to help us improve Winfr Pro
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Winfr Pro are you running? (e.g. 0.1.0 Beta)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Terminal Logs (if applicable)
      description: Copy and paste any relevant logs from the live terminal.
