name: ✨ Feature Request
description: Suggest an idea for Winfr Pro
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? We'd love to hear about it!
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Alternative Solutions/Context
      description: Any other context or screenshots about the feature request here.
